'use strict';
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const token=$('meta[name="app-token"]').content;
let selected=[],busy=false,cancelled=false,kind='items',offset=0,logOffset=0,status={notes:0,items:0,files:0,retained:0,errors:0,xlsx:false},searchTimer,requestId=0;
async function api(path,options={}){const r=await fetch(path,{...options,headers:{...options.headers,'X-App-Token':token}});if(!r.ok){const e=await r.json().catch(()=>({error:'Falha na comunicação local.'}));throw Error(e.error||'Não foi possível concluir.');}return r;}
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,6000);}
function show(page){$$('.page').forEach(x=>x.hidden=x.id!==`page-${page}`);$$('nav [data-page]').forEach(x=>{x.classList.toggle('active',x.dataset.page===page);x.setAttribute('aria-current',x.dataset.page===page?'page':'false');});if(page==='reports')loadResults();if(page==='status')loadLogs();}
$$('[data-page]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.page)));
function setTheme(dark){document.body.classList.toggle('dark',dark);$('#theme').textContent=dark?'Modo claro':'Modo escuro';$('#theme').setAttribute('aria-label',dark?'Ativar modo claro':'Ativar modo escuro');try{localStorage.setItem('xml-theme',dark?'dark':'light');}catch{}}
try{setTheme(localStorage.getItem('xml-theme')==='dark');}catch{}
$('#theme').onclick=()=>setTheme(!document.body.classList.contains('dark'));
function select(files){if(busy)return;selected=Array.from(files).filter(f=>f.name.toLowerCase().endsWith('.xml'));updateSelection();if(!selected.length)toast('Selecione arquivos com extensão .xml.');}
function updateSelection(){const bytes=selected.reduce((s,f)=>s+f.size,0);$('#selected-title').textContent=selected.length?`${selected.length} XML(s) selecionado(s)`:'Nenhum arquivo selecionado';$('#selected-detail').textContent=selected.length?`${(bytes/1048576).toLocaleString('pt-BR',{maximumFractionDigits:1})} MB · os documentos originais serão preservados.`:'Subpastas também são incluídas ao selecionar uma pasta.';$('#import').disabled=busy||!selected.length;$('#clear').disabled=busy||!selected.length;}
$('#choose-files').onclick=()=>$('#files').click();$('#choose-folder').onclick=()=>$('#folder').click();$('#files').onchange=e=>select(e.target.files);$('#folder').onchange=e=>select(e.target.files);$('#clear').onclick=()=>{selected=[];$('#files').value='';$('#folder').value='';updateSelection();};
const drop=$('#dropzone');['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();if(!busy)drop.classList.add('drag');}));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('drag');}));drop.addEventListener('drop',e=>select(e.dataTransfer.files));
function renderSummary(s){status=s;for(const k of ['notes','items','retained','errors'])$(`#stat-${k}`).textContent=(s[k]||0).toLocaleString('pt-BR');$('#nav-count').textContent=s.notes;$('#excel').disabled=busy||!s.notes||!s.xlsx;$('#log-csv').disabled=busy||!s.files;}
function lock(on){busy=on;$('#choose-files').disabled=on;$('#choose-folder').disabled=on;$('#cancel').hidden=!on;$('#import').hidden=on;updateSelection();renderSummary(status);$('#csv').disabled=on||!status.notes;}
$('#cancel').onclick=()=>{cancelled=true;$('#cancel').disabled=true;$('#cancel').textContent='Interrompendo…';};
$('#import').onclick=async()=>{if(busy||!selected.length)return;const oversized=selected.find(f=>f.size>20*1048576);if(oversized){toast(`${oversized.name}: limite de 20 MB por XML excedido.`);return;}if(selected.reduce((n,f)=>n+f.size,0)>250*1048576){toast('A seleção excede 250 MB. Importe em lotes menores.');return;}if(status.files&&!confirm('A nova importação substituirá os resultados atuais. Continuar?'))return;const list=[...selected];cancelled=false;lock(true);$('#progress-wrap').hidden=false;$('#import-result').hidden=true;$('#cancel').disabled=false;$('#cancel').textContent='Interromper';offset=0;logOffset=0;$('#progress').value=0;$('#progress-percent').textContent='0%';$('#search').value='';let processed=0;try{renderSummary(await(await api('/api/reset',{method:'POST'})).json());for(const file of list){if(cancelled)break;$('#progress-text').textContent=`${processed+1}/${list.length} · ${file.name}`;const name=file.webkitRelativePath||file.name;if(file.size>20*1048576){toast(`${file.name}: limite de 20 MB excedido. Remova o arquivo da seleção.`);cancelled=true;break;}const data=await(await api(`/api/upload?name=${encodeURIComponent(name)}`,{method:'POST',body:file})).json();renderSummary(data.summary);processed++;const pct=Math.round(processed/list.length*100);$('#progress').value=pct;$('#progress-percent').textContent=`${pct}%`;}
$('#progress-text').textContent=cancelled?'Importação interrompida. Os resultados já lidos foram mantidos.':'Importação concluída.';const notice=$('#import-result');notice.replaceChildren(document.createTextNode(`${cancelled?'Importação parcial':'Concluído'}: ${status.notes} nota(s), ${status.items} item(ns), ${status.duplicates} duplicata(s) e ${status.errors} erro(s). `));const b=document.createElement('button');b.textContent='Conferir relatórios';b.onclick=()=>show('reports');notice.append(b);notice.hidden=false;toast(cancelled?'Resultados parciais disponíveis.':'XMLs processados. Confira os relatórios.');}catch(e){toast(e.message);$('#progress-text').textContent='Processamento interrompido. Confira os arquivos já lidos.';}finally{lock(false);loadLogs();}};
$$('[data-kind]').forEach(b=>b.onclick=()=>{kind=b.dataset.kind;offset=0;$$('[data-kind]').forEach(x=>x.classList.toggle('active',x===b));loadResults();});
$('#search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{offset=0;loadResults();},220);};
function cell(text,tag='td'){const c=document.createElement(tag);c.textContent=text??'';c.title=text??'';return c;}
async function loadResults(){const id=++requestId;try{const q=encodeURIComponent($('#search').value);const data=await(await api(`/api/results?kind=${kind}&q=${q}&offset=${offset}`)).json();if(id!==requestId)return;const headers=kind==='retained'?data.fields:['Numero Nota','Data Emissao','Destinatario Razao','Item','Codigo','Descricao','NCM','CFOP','Qtd','Vl. Unitario','Vl. Total','CST ICMS','CSOSN','Vl. ICMS','Vl. PIS','Vl. COFINS'];const head=$('#results thead');head.replaceChildren();const tr=document.createElement('tr');headers.forEach(k=>tr.append(cell(k,'th')));head.append(tr);const body=$('#results tbody');body.replaceChildren();data.rows.forEach(row=>{const tr=document.createElement('tr');headers.forEach(k=>tr.append(cell(row[k])));body.append(tr);});$('#result-count').textContent=`${data.total.toLocaleString('pt-BR')} registro(s)`;$('#table-wrap').hidden=!data.total;$('#empty').hidden=!!data.total;$('#empty h2').textContent=status.notes?'Nenhum registro encontrado.':'Seus relatórios aparecerão aqui.';$('#empty p').textContent=status.notes?(kind==='retained'?'Não há retenções positivas que correspondam à busca.':'Tente outro número, chave ou descrição.'):'Importe os XMLs para conferir os itens e as retenções.';$('#page-info').textContent=data.total?`${offset+1}–${Math.min(offset+100,data.total)} de ${data.total}`:'Nenhum registro';$('#previous').disabled=offset===0;$('#next').disabled=offset+100>=data.total;$('#csv').disabled=busy||!data.total;}catch(e){toast(e.message);}}
$('#previous').onclick=()=>{offset=Math.max(0,offset-100);loadResults();};$('#next').onclick=()=>{offset+=100;loadResults();};
async function loadLogs(){try{const data=await(await api(`/api/results?kind=logs&offset=${logOffset}`)).json();const body=$('#logs tbody');body.replaceChildren();for(const row of data.rows){const tr=document.createElement('tr');tr.append(cell(row.file));const td=document.createElement('td'),badge=document.createElement('span');badge.className='badge'+(row.status==='Erro'?' error':'');badge.textContent=row.status;td.append(badge);tr.append(td,cell(row.message));body.append(tr);}$('#logs-empty').hidden=!!data.total;$('#log-info').textContent=data.total?`${logOffset+1}–${Math.min(logOffset+100,data.total)} de ${data.total} arquivos`:'0 arquivos';$('#log-previous').disabled=logOffset===0;$('#log-next').disabled=logOffset+100>=data.total;}catch(e){toast(e.message);}}
$('#log-previous').onclick=()=>{logOffset=Math.max(0,logOffset-100);loadLogs();};$('#log-next').onclick=()=>{logOffset+=100;loadLogs();};
async function download(format,which=kind){try{const q=which==='logs'?'':$('#search').value;const r=await api(`/api/export?format=${format}&kind=${which}&q=${encodeURIComponent(q)}`);const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=format==='xlsx'?'Leitor_XML.xlsx':`relatorio_${which}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Relatório enviado para os downloads do navegador.');}catch(e){toast(e.message);}}
$('#excel').onclick=()=>download('xlsx');$('#csv').onclick=()=>download('csv');$('#log-csv').onclick=()=>download('csv','logs');
window.addEventListener('beforeunload',e=>{if(busy){e.preventDefault();e.returnValue='';}});
api('/api/status').then(r=>r.json()).then(renderSummary).catch(e=>toast(e.message));
